In [3]:
import pandas as pd 
import numpy as np  
import pickle

In [4]:
ohe_sex = pickle.load(open('paras/ohe_sex.pkl','rb'))
ohe_embarked = pickle.load(open('paras/ohe_embarked.pkl','rb'))
clf = pickle.load(open('paras/clf.pkl','rb'))

In [9]:
test_input = np.array([2, 'male', 31.0, 0, 0, 10.5, 'S'],dtype=object).reshape(1,7)
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [10]:
test_input.shape

(1, 7)

In [11]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))
test_input_sex

C:\Users\hp\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0., 1.]])

In [17]:
test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))
test_input_embarked

array([[0., 0., 1.]])

In [18]:
test_input_age = test_input[:,2].reshape(1,1)
test_input_transformed = np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_input_sex,test_input_embarked),axis=1)

In [20]:
test_input_transformed.shape

array([0], dtype=int64)

In [21]:

clf.predict(test_input_transformed)

array([0], dtype=int64)