In [43]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 
from sklearn.datasets import load_diabetes


In [44]:
x,y=load_diabetes(return_X_y=True)


In [45]:
x

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [46]:
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [47]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.9)

In [48]:
x_train

array([[ 0.00175052,  0.05068012, -0.00512814, ..., -0.03949338,
        -0.0060811 , -0.06735141],
       [-0.05637009, -0.04464164,  0.09295276, ...,  0.02545259,
         0.02606052,  0.04034337],
       [ 0.09256398, -0.04464164,  0.03690653, ..., -0.03949338,
        -0.02251653, -0.02178823],
       ...,
       [-0.0854304 , -0.04464164, -0.00405033, ..., -0.03949338,
        -0.0611758 , -0.01350402],
       [ 0.02354575,  0.05068012, -0.0191397 , ..., -0.03949338,
        -0.02595311, -0.01350402],
       [ 0.08166637, -0.04464164,  0.03367309, ...,  0.03430886,
         0.03486619,  0.06933812]])

In [49]:
y_train

array([ 92., 128.,  70., 135.,  59., 148.,  74., 152.,  80.,  94., 243.,
       200., 178., 192., 185.,  90., 220., 263., 190.,  85., 277.,  89.,
       156., 237., 141.,  53.,  65.,  60.,  25.,  92., 142., 270., 113.,
       283., 200.,  77., 248.,  61., 248., 179., 144., 104., 171., 151.,
       208., 212., 140., 277.,  52., 179.,  53.,  98.,  72., 265., 158.,
       197., 170.,  75., 236., 283.,  44.,  71., 225., 141.,  81., 262.,
        52., 142., 162.,  67., 248., 118.,  91.,  66., 155., 178., 275.,
       258., 132., 115., 191., 210., 164., 332., 107., 258., 186., 249.,
       274., 177., 160., 196., 103., 172., 281., 178.,  69.,  89., 111.,
        91., 252.,  47., 202.,  51.,  99., 103., 143., 246., 230., 209.,
       109., 241.,  88., 125., 131.,  74., 123., 233.,  63., 232.,  97.,
       143., 242.,  77., 124., 242.,  87.,  67., 170., 306.,  66., 219.,
       308., 293., 233., 275.,  94., 113., 134., 181., 280., 121.,  40.,
       150., 197., 292.,  81., 182., 153.,  88.,  7

In [50]:
x_test

array([[ 1.75052192e-03, -4.46416365e-02, -4.60850009e-02,
        -3.32132301e-02, -7.31185084e-02, -8.14798836e-02,
         4.49584616e-02, -6.93832908e-02, -6.11757990e-02,
        -7.97777289e-02],
       [-9.14709343e-03, -4.46416365e-02, -6.22521820e-02,
        -7.45274418e-02, -2.35842056e-02, -1.32135190e-02,
         4.46044580e-03, -3.94933829e-02, -3.58161926e-02,
        -4.66408736e-02],
       [-7.09002471e-02, -4.46416365e-02,  9.29527567e-02,
         1.26799734e-02,  2.04462859e-02,  4.25269072e-02,
         7.78807997e-04,  3.59827672e-04, -5.45396403e-02,
        -1.07769750e-03],
       [-2.00447088e-02, -4.46416365e-02,  4.57216660e-03,
         9.76151070e-02,  5.31080447e-03, -2.07290821e-02,
         6.33666507e-02, -3.94933829e-02,  1.25511949e-02,
         1.13486232e-02],
       [-2.73097857e-02, -4.46416365e-02,  8.00190118e-02,
         9.87512478e-02, -2.94491268e-03,  1.81013272e-02,
        -1.76293810e-02,  3.31191734e-03, -2.95264268e-02,
         3.

In [51]:
y_test

array([114.,  53., 200.,  48., 257., 178., 202., 276., 164., 111.,  50.,
       268., 281.,  90., 273.,  78., 163.,  84., 295.,  85., 145., 303.,
        86., 124., 144., 310., 187.,  42., 259., 140.,  72.,  77., 317.,
       146.,  85., 175.,  55., 120., 281.,  96., 198., 198., 100., 297.,
        96.])

In [52]:
from sklearn.linear_model import LinearRegression

In [53]:
lr=LinearRegression()

In [54]:
x_trained=lr.fit(x_train,y_train)
x_trained

LinearRegression()

In [55]:
x_trained.coef_

array([ -20.85912567, -236.947057  ,  514.04839492,  360.56203219,
       -874.76832563,  571.55093426,  142.14201975,  165.35573155,
        754.77558044,   45.8843731 ])

In [56]:
x_trained.intercept_

151.7767499420782

In [84]:
class StochasticGradientDescent: 
    def __init__(self,learning_rate=0.01,epochs=100):
        self.lr=learning_rate
        self.ep=epochs
        self.coeff_=None 
        self.intercept=None 
        
    def fit(self,x,y): 
        self.intercept=0 
        self.coeff_=np.zeros(x.shape[1])
        
        for i in range(self.ep):
           indices = np.arange(x.shape[0])  # Create a list of indices
           np.random.shuffle(indices)  # Shuffle indices at the start of each epoch

           for j in indices:  # Iterate through shuffled indices
                y_pred = self.intercept + np.dot(x[j], self.coeff_)
                inter_gradient = -2 * (y[j] - y_pred)
                self.intercept = self.intercept - (self.lr * inter_gradient)
                coeff_gradient = -2 * np.dot((y[j] - y_pred), x[j])
                self.coeff_ = self.coeff_ - (self.lr * coeff_gradient)
                self.coeff_=self.coeff_-(self.lr*coeff_gradient)
                # print(f'\n\n\nThe variables after {j+1}th row calculation are== \n',self.coeff_,self.intercept,len(self.coeff_),end='\n')
            # print(f'\n\n\nAfter the {i}th epoch the value of th e coefficients are===\n',self.coeff_,self.intercept,len(self.coeff_),end='\n')
        print(f'The final value of the variables are==\n\n\n',self.coeff_,self.intercept,len(self.coeff_),end='\n')

    def predict(self,x):
        return np.dot(x,self.coeff_)+self.intercept

    

In [101]:
sgd=StochasticGradientDescent(0.01,30)
x_trained_sgd=sgd.fit(x_train,y_train) 

The final value of the variables are==


 [  23.54422499 -108.41057182  391.88802341  272.14993674   -1.28309025
  -39.8880828  -186.24591199  133.35238346  314.26669927  127.36776569] 155.3941718921904 10


In [102]:
y_pred=sgd.predict(x_test)

In [103]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.5100593717172919