In [26]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 
from sklearn.datasets import load_diabetes
import time 

In [2]:
x,y=load_diabetes(return_X_y=True)


In [3]:
x

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [4]:
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [5]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.9)

In [6]:
x_train

array([[-0.00188202,  0.05068012, -0.02452876, ..., -0.00259226,
        -0.02139531,  0.03620126],
       [ 0.02717829, -0.04464164,  0.00672779, ...,  0.03430886,
         0.04067283,  0.01134862],
       [ 0.06713621,  0.05068012, -0.02991782, ..., -0.05056372,
        -0.03845972,  0.00720652],
       ...,
       [-0.07453279, -0.04464164, -0.046085  , ..., -0.03949338,
        -0.03980883, -0.02178823],
       [-0.00188202, -0.04464164,  0.03367309, ..., -0.00259226,
         0.02671684,  0.06105391],
       [-0.0854304 , -0.04464164,  0.02073935, ..., -0.00259226,
        -0.02364686,  0.00306441]])

In [7]:
y_train

array([ 65.,  67., 108.,  74., 122., 273.,  88., 257., 232., 104.,  65.,
       253.,  99., 197.,  54., 189., 129., 151., 102., 118., 270.,  78.,
        81., 200.,  97.,  78., 143.,  97., 310., 158., 141., 233.,  88.,
       123.,  64., 248.,  66., 137., 202., 116.,  94., 127., 110., 212.,
       275., 242., 150.,  64., 150., 293.,  59.,  74., 292., 124., 244.,
        84., 132., 152., 143., 118.,  52.,  72., 200.,  81., 103., 230.,
       109., 252., 131.,  64., 206.,  90., 268.,  77.,  97., 109., 258.,
        72., 156., 288., 104., 155., 311., 265., 230.,  97.,  51.,  91.,
        53., 166.,  53., 268.,  86.,  59.,  50., 261., 147., 179.,  88.,
       162.,  77., 141., 142., 263.,  48.,  52., 168.,  31.,  49.,  96.,
       131.,  66., 225., 161.,  37., 274., 140., 292., 208., 235.,  75.,
        90.,  39.,  69., 214., 186., 145., 281., 178., 242.,  91.,  59.,
        59.,  48., 139., 128., 102., 182., 181., 125., 144.,  53., 241.,
       265., 104., 167., 164., 248.,  71., 113., 16

In [8]:
x_test

array([[-0.00551455, -0.04464164,  0.06492964,  0.03564379, -0.00156896,
         0.01496984, -0.01394774,  0.00072884, -0.01811369,  0.03205916],
       [-0.02730979, -0.04464164,  0.06492964, -0.00222757, -0.02496016,
        -0.01728445,  0.02286863, -0.03949338, -0.0611758 , -0.0632093 ],
       [-0.04183994, -0.04464164, -0.06548562, -0.04009893, -0.00569682,
         0.01434355, -0.04340085,  0.03430886,  0.00702714, -0.01350402],
       [-0.06000263,  0.05068012,  0.04984027,  0.01842953, -0.01670444,
        -0.03012354, -0.01762938, -0.00259226,  0.0497702 , -0.05906719],
       [ 0.04534098, -0.04464164, -0.00620595,  0.01154383,  0.06310082,
         0.01622244,  0.09650139, -0.03949338,  0.04289704, -0.03835666],
       [-0.02004471, -0.04464164, -0.08488624, -0.02632753, -0.03596778,
        -0.03419447,  0.04127682, -0.05167075, -0.08237869, -0.04664087],
       [-0.09996055, -0.04464164, -0.02345095, -0.06419889, -0.05798303,
        -0.06018579,  0.01182372, -0.03949338

In [9]:
y_test

array([109.,  95., 214., 221., 134.,  90., 150., 187.,  67., 246., 198.,
        49., 172., 196.,  84.,  65., 308., 248., 198.,  95., 200., 144.,
        63.,  92., 303., 310., 200.,  57., 128., 280., 128., 264., 111.,
       107., 177., 152., 341.,  90., 191., 104., 233.,  84., 115.,  51.,
        77.])

In [10]:
from sklearn.linear_model import LinearRegression

In [11]:
lr=LinearRegression()

In [12]:
x_trained=lr.fit(x_train,y_train)
x_trained

LinearRegression()

In [13]:
x_trained.coef_

array([ -14.84041355, -254.45676227,  508.23658575,  311.25522595,
       -793.22032771,  535.89452709,   69.7326903 ,   95.18300885,
        770.23575888,   76.70504582])

In [14]:
x_trained.intercept_

151.47697323142177

In [19]:
class StochasticGradientDescent: 
    def __init__(self,learning_rate=0.01,epochs=100):
        self.lr=learning_rate
        self.ep=epochs
        self.coeff_=None 
        self.intercept=None 
        
    def fit(self,x,y): 
        self.intercept=0 
        self.coeff_=np.zeros(x.shape[1])
        
        for i in range(self.ep):
           indices = np.arange(x.shape[0])  # Create a list of indices
           np.random.shuffle(indices)  # Shuffle indices at the start of each epoch

           for j in indices:  # Iterate through shuffled indices
                y_pred = self.intercept + np.dot(x[j], self.coeff_)
                inter_gradient = -2 * (y[j] - y_pred)
                self.intercept = self.intercept - (self.lr * inter_gradient)
                coeff_gradient = -2 * np.dot((y[j] - y_pred), x[j])
                self.coeff_ = self.coeff_ - (self.lr * coeff_gradient)
                self.coeff_=self.coeff_-(self.lr*coeff_gradient)
                # print(f'\n\n\nThe variables after {j+1}th row calculation are== \n',self.coeff_,self.intercept,len(self.coeff_),end='\n')
            # print(f'\n\n\nAfter the {i}th epoch the value of th e coefficients are===\n',self.coeff_,self.intercept,len(self.coeff_),end='\n')
        print(f'The final value of the variables are==\n\n\n',self.coeff_,self.intercept,self.coeff_.shape,len(self.coeff_),end='\n')

    def predict(self,x):
        return np.dot(x,self.coeff_)+self.intercept

    

In [27]:
start=time.time()
sgd=StochasticGradientDescent(0.01,30)
x_trained_sgd=sgd.fit(x_train,y_train) 
print('the time taken to train the model is ',time.time()-start)

The final value of the variables are==


 [  32.02693088 -130.07013373  383.6090796   241.34104931   10.59903599
  -38.57228332 -183.10716228  128.57436215  334.60346615  147.73109869] 159.5548690205714 (10,) 10
the time taken to train the model is  0.3394129276275635


In [22]:
y_pred=sgd.predict(x_test)

In [23]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.6239651058539208

# Applying Stochastic Gradient Descent From Sklearn 

In [28]:
from sklearn.linear_model import SGDRegressor

In [34]:
sgd=SGDRegressor(max_iter=100,learning_rate='constant',random_state=42)
sgd.fit(x_train,y_train)

C:\Users\hp\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_stochastic_gradient.py:1616: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  warnings.warn(


SGDRegressor(learning_rate='constant', max_iter=100, random_state=42)

In [35]:
y_pred=sgd.predict(x_test)

In [36]:
y_pred 

array([189.9257709 , 142.01204916, 136.33693801, 177.00208139,
       147.08790111,  75.6757634 , 111.68564139, 136.90373689,
       133.90530737, 209.74690879, 169.42706321, 112.64942501,
       169.00647074, 182.92552732,  96.26492768,  67.45679611,
       233.14075109, 223.47783845, 193.30161627, 155.12396799,
       125.35869512, 172.86728767, 110.22061589, 102.63188028,
       231.49543832, 253.15127959, 173.22670148,  77.67664172,
       165.82050605, 201.85401765,  92.06080047, 234.54158095,
       143.07038847, 137.71245633, 143.67905431,  95.55457591,
       234.66786238, 103.13922312, 173.41229073, 161.54107143,
       236.59099862, 125.82291668, 155.90841475,  90.17744048,
        90.81489292])

In [37]:
r2_score(y_test,y_pred)

0.6541237180736328