In [28]:
import pandas as pd 
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt 
from sklearn.datasets import load_diabetes

In [29]:
x,y=load_diabetes(return_X_y=True)
x

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [30]:
x.shape

(442, 10)

In [31]:
y.shape 

(442,)

In [32]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.9,random_state=42)


In [33]:
x_train.shape

(397, 10)

In [34]:
x_test.shape 

(45, 10)

In [35]:
from sklearn.linear_model import LinearRegression

lr=LinearRegression()
x_trained=lr.fit(x_train,y_train)
x_trained

LinearRegression()

In [36]:
x_trained.intercept_

151.7226464572191

In [37]:
x_trained.coef_

array([  19.92730105, -262.5526422 ,  509.19584695,  336.09319329,
       -849.30479304,  480.22664735,  120.69064852,  236.72228404,
        716.61278802,   70.41001991])

In [38]:
y_pred=x_trained.predict(x_test)
y_pred

array([143.06549158, 177.7061702 , 134.79901866, 288.67009951,
       123.58658064,  96.64279345, 252.70727574, 183.51437294,
        93.96679126, 109.83567271,  98.04584067, 168.6157848 ,
        58.09603726, 206.59004617, 102.4046759 , 130.25483366,
       218.05518616, 245.91819051, 193.24561396, 214.36953807,
       208.82839114,  90.55628576,  74.15157442, 187.12342576,
       156.3642741 , 157.46594185, 184.17437321, 177.18270901,
        52.24311033, 110.66618343, 174.05770617,  90.8969391 ,
       133.07838489, 183.22702102, 173.93636697, 189.8528273 ,
       125.8627716 , 121.53079768, 148.94645924,  60.82914409,
        76.36004131, 106.39774469, 162.2028406 , 153.15220926,
       174.23219731])

In [39]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.5514200923362625

In [41]:
class BatchGradientDescent:
    def __init__(self,learning_rate=0.001,epoch=150): 
        self.lr=learning_rate
        self.ep=epoch
        self.coeff_=None 
        self.intercept=None 

    def fit(self,x,y):
        self.intercept=0 
        self.coeff_=np.ones(x.shape[1])
        
        for i in range(self.ep): 
            y_pred=self.intercept+np.dot(x,self.coeff_)
            inter_gradient=-2*np.mean(y-y_pred) 
            self.intercept=self.intercept-(self.lr*inter_gradient)
            coeff_gradient=-2*np.dot((y-y_pred),x)
            self.coeff_=self.coeff_-(self.lr*coeff_gradient)
        print(self.coeff_,self.intercept,len(self.coeff_))
    
    def predict(self,x):
        return (x*self.coeff_)+self.intercept
        

In [43]:
bgd=BatchGradientDescent(0.1,100)
bgd.fit(x_train,y_train)


[  21.26514018 -260.54145757  518.87162867  333.42381952 -174.18848886
  -55.7977805  -175.67860383  154.61338485  463.73909565   72.76724731] 151.75177010792362 10


In [44]:
y_pred=bgd.predict(x_test)

array([[152.71595247, 163.38276715, 148.53167658, 146.41733068,
        129.97495113, 144.76599394, 148.38102526, 157.05637891,
        166.79190678, 151.37193931],
       [153.72015619, 163.38276715, 170.90152082, 159.04454443,
        156.09954238, 152.68125802, 151.61495021, 145.6455645 ,
        141.3099756 , 150.16630044],
       [153.10218467, 138.5474981 , 149.65016879, 147.5652592 ,
        133.80975352, 149.02940329, 141.91317537, 151.35097171,
        190.93379613, 150.46771015],
       [153.79740263, 163.38276715, 178.73096631, 178.1805129 ,
        142.19838373, 149.71084987, 165.19743498, 173.6020598 ,
        197.49873294, 156.1944948 ],
       [152.02073452, 138.5474981 , 141.2614772 , 151.00904477,
        145.07448552, 148.78478144, 152.90852018, 157.05637891,
        149.36713566, 151.07052959],
       [151.94348808, 163.38276715, 139.02449277, 142.97354511,
        134.52877896, 146.49581987, 139.32603541, 151.35097171,
        141.82992874, 152.27616846],
       [15

In [46]:
r2_score(y_test,y_pred)

0.5514200923362625