In [1]:
import pandas as pd 
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt 




In [2]:
df=pd.read_csv('salary.csv')
df

YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [3]:
df2=df.sample(5) 
df2

YearsExperience    Salary
9               3.7   57189.0
15              4.9   67938.0
0               1.1   39343.0
2               1.5   37731.0
22              7.9  101302.0

In [4]:
from sklearn.linear_model import LinearRegression

ml=LinearRegression()
x_trained=ml.fit(df2[['YearsExperience']],df2['Salary'])
x_trained

LinearRegression()

In [5]:
x=df2[['YearsExperience']]
y=df2['Salary']

In [6]:
m=x_trained.coef_
m

array([9320.23131208])

In [7]:
b=x_trained.intercept_
b

25097.31638787245

In [8]:
y_pred=m*x+b 
y_pred 

YearsExperience
9      59582.172243
15     70766.449817
0      35349.570831
2      39077.663356
22     98727.143753

In [9]:
y_pred1=m*x.to_numpy().ravel()+b
y_pred1

array([59582.17224255, 70766.44981704, 35349.57083116, 39077.66335599,
       98727.14375327])

# Using LinearRegression To train our model 

In [10]:
#Training model for linear regression 

from sklearn.linear_model import LinearRegression

ml=LinearRegression()

x=df[['YearsExperience']]
y=df['Salary']
x_trained=ml.fit(x,y,sample_weight=None)
x_trained



LinearRegression()

In [11]:
#Slope
m=x_trained.coef_
m

array([9449.96232146])

In [12]:
b=x_trained.intercept_
b

25792.20019866871

# Gradeint Descent Calculator 

In [13]:
class GradientDescentCalculator:
    def __init__(self,learning_rate,epochs):
        self.m=m
        self.b=100
        self.lr=learning_rate
        self.ep=epochs 

    def calculator(self,x,y):
       for i in range(self.ep):
        y_pred=(self.m*x.to_numpy().ravel())+self.b
        slope=-2*(np.sum(y-y_pred))/df.shape[0]  
        step_size=self.lr*slope
        self.b=self.b-step_size
        print(slope,step_size,self.b)
       print(self.b)


In [14]:
gd=GradientDescentCalculator(0.001,3000)

In [15]:
gd.calculator(x,y)

-51384.40039733742 -51.38440039733742 151.38440039733743
-51281.63159654276 -51.28163159654276 202.66603199388018
-51179.06833334965 -51.17906833334965 253.84510032722983
-51076.71019668295 -51.07671019668295 304.92181052391277
-50974.55677628958 -50.97455677628958 355.89636730020237
-50872.60766273701 -50.87260766273702 406.7689749629394
-50770.862447411535 -50.77086244741154 457.53983741035097
-50669.32072251672 -50.66932072251672 508.2091581328677
-50567.98208107168 -50.567982081071676 558.7771402139393
-50466.84611690954 -50.46684611690954 609.2439863308489
-50365.91242467573 -50.36591242467573 659.6098987555246
-50265.180599826366 -50.265180599826365 709.875079355351
-50164.65023862673 -50.164650238626734 760.0397295939777
-50064.32093814946 -50.064320938149464 810.1040505321271
-49964.19229627317 -49.96419229627317 860.0682428284002
-49864.263911680624 -49.864263911680624 909.9325067400808
-49764.53538385725 -49.76453538385725 959.6970421239381
-49665.00631308954 -49.665006313089

# Varying Both m and b 

In [22]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation

class GradientDescentCalculator:
    def __init__(self, learning_rate, epochs):
        self.m = 0  # Initialize slope
        self.b = 100  # Initialize intercept
        self.lr = learning_rate
        self.ep = epochs

    def calculator(self, x, y):
        x = x.to_numpy().ravel()
        n = len(y)
        for _ in range(self.ep):
            y_pred = self.m * x + self.b
            # Gradients
            gradient_m = (-2/n) * np.sum(x * (y - y_pred))
            gradient_b = (-2/n) * np.sum(y - y_pred)
            self.m -= self.lr * gradient_m
            self.b -= self.lr * gradient_b
            print(gradient_b,gradient_m,self.b,self.m)
        print(self.b,self.m)
            

In [27]:
# Initialize calculator with adjusted learning rate (larger for visualization)
gd = GradientDescentCalculator(learning_rate=0.01, epochs=4000)
gd.calculator(x, y)  

-151806.0 -953734.7333333333 1618.06 9537.347333333333
-47419.669004444455 -250595.89615555562 2092.2566900444444 12043.30629488889
-19841.285059558515 -65044.18879863135 2290.6695406400295 12693.748182875202
-12532.43022869946 -16082.224241688238 2415.993842927024 12854.570425292084
-10572.7772613754 -3165.8824606223925 2521.721615540778 12886.229249898308
-10024.89393999909 238.14200215476254 2621.970554940769 12883.84782987676
-9849.70261796142 1131.9124426265364 2720.4675811203833 12872.528705450495
-9772.993127838643 1363.2532446565765 2818.19751239877 12858.89617300393
-9722.401643414032 1419.7998938073056 2915.42152883291 12844.698174065858
-9678.831012594337 1430.2379182749737 3012.2098389588537 12830.395794883108
-9637.241008457795 1428.5269800826597 3108.5822490434316 12816.110525082282
-9596.300988705418 1423.6288565952661 3204.545258930486 12801.874236516329
-9555.659262092167 1417.9084552942136 3300.1018515514074 12787.695151963388
-9515.222482032927 1411.9897889156205 339