In [1]:
import pandas as pd 
import numpy as np  
import matplotlib.pyplot as plt 

In [2]:
from sklearn.datasets import load_diabetes
x,y=load_diabetes(return_X_y=True)


In [3]:
x

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [5]:
y


array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [22]:
from sklearn.model_selection import train_test_split 
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8)


In [23]:
x_train

array([[ 0.06713621, -0.04464164, -0.03854032, ..., -0.03949338,
        -0.02712902,  0.00306441],
       [ 0.03807591,  0.05068012,  0.0164281 , ...,  0.07120998,
         0.0497702 ,  0.01549073],
       [ 0.06713621,  0.05068012, -0.03638469, ...,  0.03430886,
         0.00114758,  0.03205916],
       ...,
       [ 0.01991321,  0.05068012, -0.01267283, ...,  0.03430886,
         0.00538633,  0.00306441],
       [-0.07816532, -0.04464164, -0.01698407, ..., -0.03949338,
        -0.04117617, -0.09220405],
       [ 0.01628068, -0.04464164,  0.01750591, ..., -0.00259226,
         0.03723625, -0.0010777 ]])

In [24]:
x_test

array([[ 0.07440129, -0.04464164,  0.01858372,  0.0631866 ,  0.06172487,
         0.04284006,  0.00814208, -0.00259226,  0.05803805, -0.05906719],
       [-0.00188202,  0.05068012,  0.03043966,  0.05285804,  0.03970963,
         0.05661859, -0.03971921,  0.07120998,  0.02539508,  0.02791705],
       [-0.02730979, -0.04464164, -0.06656343, -0.1123988 , -0.04972731,
        -0.04139688,  0.00077881, -0.03949338, -0.03581619, -0.00936191],
       [ 0.0090156 , -0.04464164,  0.04552903,  0.02875809,  0.01219057,
        -0.01383982,  0.02655027, -0.03949338,  0.04613307,  0.03620126],
       [-0.00188202, -0.04464164, -0.06979687, -0.01255612, -0.00019301,
        -0.00914259,  0.07072993, -0.03949338, -0.06291688,  0.04034337],
       [ 0.03807591,  0.05068012, -0.00943939,  0.00235142,  0.00118295,
         0.03751653, -0.05444576,  0.05017634, -0.02595311,  0.10661708],
       [-0.09269548, -0.04464164, -0.04069594, -0.01944183, -0.06899065,
        -0.07928784,  0.04127682, -0.0763945 

In [25]:
y_train

array([127., 212., 102., 100.,  53., 172., 109.,  81.,  49.,  91.,  61.,
        98., 160., 126.,  88., 185., 332., 107., 116., 270., 144.,  65.,
       170., 275., 102.,  91., 295., 283., 152., 274.,  84., 252.,  72.,
       129., 115., 336.,  90.,  84., 198., 197., 257.,  95.,  91., 173.,
       128.,  58., 158., 151., 139., 104., 197., 281., 308., 202., 220.,
       137., 144., 150., 242., 235., 192., 199., 233., 179.,  47.,  72.,
        74.,  42., 258., 118., 134.,  78., 248., 242., 196., 115., 140.,
       142.,  75., 220., 141.,  55., 110., 166., 168.,  71., 310., 281.,
       346., 297.,  92.,  71.,  65., 131., 132.,  40.,  90., 136.,  94.,
       275.,  68.,  70.,  66., 121., 155.,  71.,  43.,  90., 276., 195.,
        53., 275., 198., 246.,  53., 237., 178., 253.,  69., 243.,  97.,
       219., 140.,  60.,  59., 109., 191., 175., 217., 150.,  59., 139.,
       113.,  77.,  96.,  78.,  87.,  78.,  70., 259., 125.,  64., 184.,
       252.,  93., 128.,  89., 233.,  80.,  42., 10

In [26]:
y_test

array([248., 222.,  77., 202.,  48.,  81.,  97., 263., 198., 142., 270.,
       268., 178., 170., 206.,  74., 310., 281., 141.,  51., 317., 145.,
       116., 216., 229., 249., 164., 168.,  64., 190., 185., 292., 108.,
       151.,  71., 129.,  44.,  86., 104., 142.,  88., 103., 113.,  64.,
       243., 245., 178.,  97., 173., 220., 143., 293., 179., 208., 138.,
       230., 120., 128.,  48., 306.,  87., 302., 232.,  84., 230.,  93.,
       103., 283., 150., 219., 272., 144.,  66., 321., 296., 134.,  31.,
       181., 262.,  84., 341.,  94.,  52., 121., 109., 265.,  83., 265.,
       174.])

In [34]:
from sklearn.linear_model import LinearRegression

model=LinearRegression()
x_trained=model.fit(x_train,y_train)
x_trained

LinearRegression()

In [37]:
x_trained.coef_

array([  24.13966613, -189.57682026,  503.3428715 ,  293.41057552,
       -695.06667392,  379.38990262,   41.73109578,  121.311653  ,
        711.4616004 ,   51.2208341 ])

In [38]:
x_trained.intercept_

149.54604818996813

In [35]:
y_pred=x_trained.predict(x_test)
y_pred 

array([199.34055477, 191.08184982,  79.00495285, 206.8505288 ,
        71.27743575, 141.01852895, 105.67986625, 257.87348614,
       157.14744112, 185.67702213, 225.90348601, 202.10538763,
       186.28465342, 134.81390433, 157.83314823,  90.92267091,
       251.6365607 , 224.80854993, 164.74505482,  80.03893456,
       216.75918164, 127.38923186, 138.03312226, 163.80198721,
       183.06063503, 199.46572101, 181.41082053, 138.39199289,
        88.77387393, 163.70590629, 164.71972447, 190.20654676,
       107.50108433, 206.99090749, 121.65493684, 113.75530226,
       129.04377529, 150.27678852,  77.81725632, 135.28786286,
       117.08609771, 124.07843724, 150.09083354, 114.75346185,
       242.7734597 , 251.10870556, 133.36932705, 107.93320472,
       209.07197637, 197.16103804,  68.33743953, 193.6879272 ,
       113.54118111, 229.18478901,  77.38140596, 133.18457183,
       157.60494695,  96.33621058,  52.74819316, 235.07618244,
        87.84317525, 142.9392299 , 228.84622656, 122.76

In [36]:
r2_score(y_test,y_pred)

0.5748104566097353

In [19]:

class MBGcalculator:
    def __init__(self, learning_rate=0.01, epochs=100, mini_batch=32):
        self.lr = learning_rate
        self.ep = epochs
        self.mb = mini_batch
        self.coeff_ = None
        self.intercept = None  # Retained your variable name

    def fit(self, x, y):
        # Initialize coefficients to match feature count
        self.intercept = 0  # Original name "intercept" preserved
        self.coeff_ = np.ones(x.shape[1])  # Critical fix: x.shape[1] not x.shape[0]

        for i in range(self.ep):
            # Shuffle data at every epoch (fixes ordering bias)
            indices = np.random.permutation(x.shape[0])  # Corrected typo
            x_shuffled = x[indices]
            y_shuffled = y[indices]

            if self.mb == 1:
                # Stochastic Gradient Descent (SGD)
                for j in range(x_shuffled.shape[0]):
                    x_j = x_shuffled[j]
                    y_j = y_shuffled[j]

                    # Prediction and gradients (retained your formula style)
                    y_pred = self.intercept + np.dot(x_j, self.coeff_)
                    inter_gradient = -2 * (y_j - y_pred)  # Original variable name
                    coeff_gradient = -2 * (y_j - y_pred) * x_j  # Fixed element-wise multiplication

                    # Parameter updates (no duplicate updates)
                    self.intercept -= self.lr * inter_gradient
                    self.coeff_ -= self.lr * coeff_gradient

            else:
                # Mini-Batch Gradient Descent (fixed batch logic)
                num_batches = x_shuffled.shape[0] // self.mb
                for batch in range(num_batches):
                    # Get mini-batch (fixed indexing)
                    start = batch * self.mb
                    end = start + self.mb
                    x_batch = x_shuffled[start:end]
                    y_batch = y_shuffled[start:end]

                    # Batch prediction and gradients
                    y_pred = self.intercept + np.dot(x_batch, self.coeff_)
                    error = y_batch - y_pred

                    # Gradients averaged over batch (retained your naming)
                    inter_gradient = -2 * np.mean(error)
                    coeff_gradient = -2 * np.dot(error, x_batch) / x_batch.shape[0]

                    # Update parameters
                    self.intercept -= self.lr * inter_gradient
                    self.coeff_ -= self.lr * coeff_gradient

        print(f"Final coefficients: {self.coeff_}, Intercept: {self.intercept}")

    def predict(self, x):
        # Corrected prediction formula (critical fix)
        return np.dot(x, self.coeff_) + self.intercept  # NOT element-wise multiplication

In [27]:
mbgd=MBGcalculator(0.01,100,30)
x_trained=mbgd.fit(x_train,y_train)
x_trained

Final coefficients: [ 13.54864584   4.23893833  42.92323085  31.48575966  12.60847366
   9.32934408 -26.52033054  27.98970709  40.98104992  23.25020831], Intercept: 148.90074934156115


In [28]:
y_pred=mbgd.predict(x_test)
y_pred 

array([154.40127878, 157.82612384, 138.12072117, 152.64071508,
       140.5854462 , 153.92886738, 136.32666015, 160.9176942 ,
       154.00713133, 153.94649501, 157.34084565, 155.98873141,
       154.62472399, 151.66110157, 150.96329444, 138.01241334,
       164.36844154, 161.85879107, 147.42915076, 137.12346473,
       160.55094749, 147.41441396, 153.78446523, 148.11569218,
       157.62930173, 158.78855356, 154.47628964, 142.90620013,
       143.3713306 , 154.50763842, 150.42500595, 159.5098002 ,
       145.60313496, 153.56988142, 149.02788589, 142.67377093,
       146.24934147, 144.97599635, 140.17890744, 152.66057025,
       145.09676391, 144.06636476, 147.92141645, 139.90797112,
       160.77032739, 165.29512523, 144.11182592, 143.79602747,
       157.65753096, 155.63127945, 133.48120302, 149.68962612,
       142.71572725, 157.02423652, 140.63819332, 152.26944925,
       156.72657117, 142.76044196, 134.23423986, 163.18886511,
       139.32971753, 146.03862117, 156.469897  , 149.88

In [39]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.5748104566097353